config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
root to: 'homes#top'
get "search" => "searches#search"
resources :customers, only: [:index,:show,:edit,:update] do
  get 'order_index' => 'customers#order_index'
end
resources :items
resources :genres, except: [:new, :show]
resources :orders, only: [:show, :update]
resources :order_details, only: [:update]
end

 root to: 'public/homes#top'
 get 'about' =>'public/homes#about'
 get "search" => "public/searches#search"

 scope module: :public do
 resources :addresses
 get "/customers/mypage" => "customers#show"
 get "/customers/edit" => "customers#edit"
 resources :customers #, except: [:show]

 # 退会確認画面＆論理削除用のルーティング
 get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
 patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'

 resources :items, only: [:index, :show]
 resources :orders, only: [:new, :create, :index, :show] do
 collection do
 post 'comfirm' => 'orders#comfirm'
 get 'complete' => 'orders#complete'
 end
 end
 resources :cart_items, only: [:index, :create, :destroy, :update,] do
 collection do
 delete 'destroy_all' => 'cart_items#destroy_all'
 end
 end
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name_kana, format: { with:  /\A[\p{katakana}\p{blank}ー－]+\z/ }
  validates :first_name_kana, format: { with:  /\A[\p{katakana}\p{blank}ー－]+\z/ }

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

# is_deletedがfalseならtrueを返すようにしている、
  #退会したら再度ログインできないようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

 def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "#{@customer.last_name + @customer.first_name}さんの会員情報を更新しました"
       redirect_to admin_customer_path(@customer.id)
    else
       render :edit
    end
 end

 def order_index
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders.order("created_at DESC").page(params[:page]).per(10)
 end


 private
 def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
 end
end

app/views/admin/customers/edit.html.erb
<div><%= render 'layouts/errors', obj: @customer %></div>
<div class="container py-3">
  <div class="row">
    <h3 class="mini-title mt-3"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h3>
  </div>

  <div class="row px-5 mx-5 mt-4">
    <div class="col-9">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
      <div class="form-group row">
        <label class="col-3">会員ID</label>
        <label class="col-3"><%= @customer.id %></label>
      </div>
      <div class="form-group row">
        <%= f.label :氏名, class: "col-3" %>
          <%= f.text_field :last_name, autocomplete: "last_name", class: "form-control col-3 mr-3" %>
          <%= f.text_field :first_name, autocomplete: "first_name", class: "form-control col-3" %>
      </div>
      <div class="form-group row">
        <%= f.label :フリガナ, class: "col-3" %>
          <%= f.text_field :last_name_kana, autocomplete: "last_name_kana", class: "form-control col-3 mr-3" %>
          <%= f.text_field :first_name_kana, autocomplete: "first_name_kana", class: "form-control col-3" %>
      </div>
      <div class="form-group row">
          <%= f.label :postal_code, '郵便番号', class: "col-3" %>
          <%= f.text_field :postal_code, autocomplete: "postal_code", class: "form-control col-3" %>
      </div>
      <div class="form-group row">
          <%= f.label :address, '住所', class: "col-3" %>
          <%= f.text_field :address, autocomplete: "address", class: "form-control col-9" %>
      </div>
      <div class="form-group row">
          <%= f.label :telephone_number, '電話番号', class: "col-3" %>
          <%= f.text_field :telephone_number, class: "form-control col-3" %>
      </div>
      <div class="form-group row">
          <%= f.label :email, 'メールアドレス', class: "col-3" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control col-3" %>
      </div>
      <div class="form-group row">
        <%= f.label :is_deleted, '会員ステータス', class: "col-3" %>
        <div class="custom-control custom-radio">
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_active, "有効", class: "mr-3" %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_active, "退会" %>
        </div>
      </div>
      <div class="actions mb-5 mt-5">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="mini-title">会員一覧</div>
    </div>
  </div>
    <div class="row justify-content-center">
      <div class="col-11">
        <table class="table table-bordered table-hover text-center">
          <thead class="thead">
            <tr>
              <th style="width: 10%">会員ID</th>
              <th style="width: 30%">氏名</th>
              <th style="width: 30%">メールアドレス</th>
              <th style="width: 30%">会員ステータス</th>
            </tr>
          </thead>
          <tbody class="tbody">
          <% @customers.each do |customer| %>
            <tr onclick='window.location="<%= '/admin/customers/' + customer.id.to_s %>"' role="link">
              <td><%= customer.id %></td>
              <td>
              <%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class: "text-dark" %>
              </td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.active_for_authentication? %>
                  <b class="text-success">有効</b>
                <% else %>
                  <b class="text-muted">退会</b>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center">
        <%= paginate @customers %>
    </div>
</div>

app/views/admin/customers/order_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="mini-title"><%= @customer.last_name + @customer.first_name %>さんの注文履歴</div>
    </div>
    </div>
      <table class="table table-bordered table-hover text-center">
        <thead class="thead">
          <tr>
           <th>購入日時</th>
           <th>注文個数</th>
           <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody class="tbody">
          <% @orders.each do |order| %>
          <tr>
           <td><%= link_to admin_order_path(order.id) do %>
                <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
               <% end %>
           <td><%= order.order_details.sum(:amount) %></td>
           <td><%= order.status_i18n %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="mini-title">
      <%= @customer.last_name + @customer.first_name %>さんの会員詳細
    </div>
  </div>
  <div class="row">
    <div class="col-8 ml-5">
      <table class="table table-bordered ml-5">
        <tbody>
          <tr>
            <th class="col-4 text-center">会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">氏名</th>
            <td>
              <%= @customer.last_name + " " + @customer.first_name %>
            </td>
          </tr>
          <tr>
            <th class="col-4 text-center">フリガナ</th>
            <td>
              <%= @customer.last_name_kana + " " + @customer.first_name_kana%>
            </td>
          </tr>
          <tr>
            <th class="col-4 text-center">郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">会員ステータス</th>
            <td>
              <% if @customer.active_for_authentication? %>
                <b class="text_success">有効</b>
              <% else %>
                <b class="text-muted">退会</b>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="mt-4 mb-4 text-center">
      <%= link_to "編集する", edit_admin_customer_path(params[:id]), class: "btn btn-success mr-3" %>
    <%= link_to "#{@customer.last_name + @customer.first_name}さんの注文履歴一覧を見る", admin_customer_order_index_path(@customer), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>