config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
root to: 'homes#top'
get "search" => "searches#search"
resources :customers, only: [:index,:show,:edit,:update] do
  get 'order_index' => 'customers#order_index'
end
resources :items
resources :genres, except: [:new, :show]
resources :orders, only: [:show, :update]
resources :order_details, only: [:update]
end

 root to: 'public/homes#top'
 get 'about' =>'public/homes#about'
 get "search" => "public/searches#search"

 scope module: :public do
 resources :addresses
 get "/customers/mypage" => "customers#show"
 get "/customers/edit" => "customers#edit"
 resources :customers #, except: [:show]

 # 退会確認画面＆論理削除用のルーティング
 get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
 patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'

 resources :items, only: [:index, :show]
 resources :orders, only: [:new, :create, :index, :show] do
 collection do
 post 'comfirm' => 'orders#comfirm'
 get 'complete' => 'orders#complete'
 end
 end
 resources :cart_items, only: [:index, :create, :destroy, :update,] do
 collection do
 delete 'destroy_all' => 'cart_items#destroy_all'
 end
 end
 end
end

app/models/order.rb
class Order < ApplicationRecord
   belongs_to :customer
   has_many :order_details, dependent: :destroy
   has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, payment_confirm: 1, making: 2, ready_to_ship: 3, sending: 4 }

  with_options presence: true do
    validates :customer_id
    validates :postal_code
    validates :address
    validates :name
    validates :shipping_fee
    validates :total_payment
    validates :payment_method
    validates :status
  end

  def status_display
    status_i18n
  end

  # 小計計算メソッド
  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @customer = Customer.find_by(id: @order.customer_id)
    @order_detail = @order.order_details.find_by(order_id: @order.id)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
      if @order.status == "payment_confirm"
         @order_details.update_all("making_status = 1")
      end
    flash[:notice] = "注文ステータスを更新しました"
    redirect_to request.referer
  end

  private

  def order_params
      params.require(:order).permit(:status)
  end
end

app/views/admin/orders/show.html.erb
<div class="container py-3">
  <div class="row">
    <h3 class="mini-title mb-3">注文履歴詳細</h3>
      <table class="table table-bordered mx-5">
        <tbody>
          <tr>
            <th>購入者</th>
            <td><%= link_to admin_customer_path(@customer.id) do %>
                  <%= @customer.last_name + " " +  @customer.first_name %>様
                <% end %>
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>
              <p><%= "〒#{@order.postal_code} #{@order.address}" %><br>
                 <%= @order.name %>
              </p>
            </td>
          </tr>
          <tr>
            <th>支払い方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td>
              <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
                <%= f.select :status, Order.statuses_i18n.invert %>
                <%= f.submit '更新', class: "btn btn-success ml-4" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-8">
        <table class="table table-bordered text-center">
          <thead class="table-warning">
            <tr>
              <th>商品</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
            </tr>
          </thead>
          <tbody class="table-danger">
            <% @order.order_details.all.each do |order_detail| %>
              <tr>
                <td class="align-middle"><%= order_detail.item.name %></td>
                <td class="align-middle"><%= (order_detail.item.with_tax_price).to_s(:delimited) %>円</td>
                <td class="align-middle"><%= order_detail.amount %> 個</td>
                <td class="align-middle"><%= (order_detail.item.with_tax_price*order_detail.amount).to_s(:delimited) %>円</td>
                <td class="align-middle"><%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                      <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                      <%= f.submit '更新', class: "btn btn-success ml-2" %>
                    <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-4">
        <table class="table table-bordered mx-5">
          <tr>
            <th>商品合計</th>
            <td><%= @order.total_payment.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.shipping_fee.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td><%= (@order.total_payment + @order.shipping_fee).to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
    </div>
</div>