config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
root to: 'homes#top'
get "search" => "searches#search"
resources :customers, only: [:index,:show,:edit,:update] do
  get 'order_index' => 'customers#order_index'
end
resources :items
resources :genres, except: [:new, :show]
resources :orders, only: [:show, :update]
resources :order_details, only: [:update]
end

 root to: 'public/homes#top'
 get 'about' =>'public/homes#about'
 get "search" => "public/searches#search"

 scope module: :public do
 resources :addresses
 get "/customers/mypage" => "customers#show"
 get "/customers/edit" => "customers#edit"
 resources :customers #, except: [:show]

 # 退会確認画面＆論理削除用のルーティング
 get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
 patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'

 resources :items, only: [:index, :show]
 resources :orders, only: [:new, :create, :index, :show] do
 collection do
 post 'comfirm' => 'orders#comfirm'
 get 'complete' => 'orders#complete'
 end
 end
 resources :cart_items, only: [:index, :create, :destroy, :update,] do
 collection do
 delete 'destroy_all' => 'cart_items#destroy_all'
 end
 end
 end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %>がありました</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="border-top border-dark pt-2">
<div class="container">
  <div class="row social">
    <div class="mx-auto">
      <%= link_to "https://twitter.com/?lang=ja" do %>
        <i class="fab fa-twitter-square fa-2x mr-3"></i>
      <% end %>
      <%= link_to "https://www.facebook.com/" do %>
        <i class="fab fa-facebook-square fa-2x mr-3"></i>
      <% end %>
      <%= link_to "https://www.instagram.com/" do %>
        <i class="fab fa-instagram fa-2x"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <p class="mx-auto">〒×××-××××<br>
      長野県××市××町×-××-×<br>
      ×××-×××-××××<br>
      定休日：火曜(祝日時は営業)・木曜<br>
      営業時間：××時～××時<br>
      ©2022 NaganoCake produced by team noodle</p>
  </div>
</div>
</div>

app/views/layouts/_header_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark" >
  <div class="container">
    <a class="navbar-brand" href="/admin"><span>Nagano Cake 管理者</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <div class="menu">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to admin_items_path, class: "nav-link" do %><i class="fas fa-birthday-cake"></i>商品一覧<% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_customers_path, class: "nav-link" do %><i class="fas fa-address-book"></i>会員一覧<% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_root_path, class: "nav-link" do %><i class="fas fa-receipt"></i>注文履歴一覧<% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_genres_path, class: "nav-link" do %><i class="fas fa-bars"></i>ジャンル一覧<% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %><i class="fas fa-sign-out-alt"></i>ログアウト<% end %>
            </li>
          </ul>
          <div class="search input-group"><!--検索窓-->
            <%= form_with(url: admin_search_path, local: true, method: :get) do |f| %>
              <%= f.text_field :word, placeholder: "Search" %>
              <%= f.button :type => "submit", class: "btn btn-outline-warning" do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header_customer.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark" >
  <div class="container">
    <a class="navbar-brand" href="/"><span>Nagano Cake</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <div class="my-auto mr-4">
          ようこそ、<%= current_customer.last_name + " " + current_customer.first_name %>さん！
        </div>
        <div class="menu">
          <ul class="navbar-nav mb-2">
            <li>
              <%= link_to customers_mypage_path, class: 'nav-link btn btn-outline-secondary mr-2' do %><i class="fas fa-house-user"></i>マイページ<% end %>
            </li>
            <li>
              <%= link_to items_path, class: 'nav-link btn btn-outline-secondary mr-2' do %><i class="fas fa-birthday-cake"></i>商品一覧<% end %>
            </li>
            <li>
              <%= link_to cart_items_path, class: 'nav-link btn btn-outline-secondary mr-2' do %><i class="fas fa-cart-arrow-down"></i>カート<% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary' do %><i class="fas fa-sign-out-alt"></i>ログアウト<% end %>
            </li>
          </ul>
          <div class="search input-group"><!--検索窓-->
            <%= form_with(url: search_path, local: true, method: :get) do |f| %>
              <%= f.text_field :word, placeholder: "Search" %>
              <%= f.button :type => "submit", class: "btn btn-outline-warning" do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header_visitor.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark" >
  <div class="container">
    <a class="navbar-brand" href="/"><span>Nagano Cake</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <div class="menu">
          <ul class="navbar-nav mb-2">
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link btn btn-outline-secondary mr-2' do %><i class="fas fa-store-alt"></i>about<% end %>
            </li>
            <li class="nav-item">
              <%= link_to items_path, class: 'nav-link btn btn-outline-secondary mr-2' do %><i class="fas fa-birthday-cake"></i>商品一覧<% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_registration_path, class: 'nav-link btn btn-outline-secondary mr-2' do %><i class="fas fa-user-plus"></i>新規登録<% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_customer_session_path, class: 'nav-link btn btn-outline-secondary' do %><i class="fas fa-sign-in-alt"></i>ログイン<% end %>
            </li>
          </ul>
          <div class="search input-group"><!--検索窓-->
            <%= form_with(url: search_path, local: true, method: :get) do |f| %>
              <%= f.text_field :word, placeholder: "Search" %>
              <%= f.button :type => "submit", class: "btn btn-outline-warning" do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
<div class="bg-warning d-flex justify-content-center">
 <%= notice %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="viewer">
      <header>
      <% if current_customer == nil && current_admin == nil %>
        <%= render 'layouts/header_visitor' %>
      <% elsif current_customer == nil && current_admin.present? %>
        <%= render 'layouts/header_admin' %>
      <% else current_customer == true && current_admin == nil %>
        <%= render 'layouts/header_customer' %>
      <% end %>
      </header>
      <main class="mb-0">
        <div><%=render "layouts/notice" %></div>
        <%= yield %>
      </main>
      <footer>
        <%= render "layouts/footer" %>
      </footer>
    </div>
  </body>
</html>